<?php

// Folder where TrackYou will be uploading GCC Gritting data
$folderTrackYouUpload = '/path/to/trackyou-uploads';

// Uncompressed TrackYou .ZIP XML files
$folderTrackYouUncompressed = '/path/to/trackyou-uncompressed';

// Folder where TrackYou XML data has been encrypted and made ready for public 
// sharing
$folderTrackYouOpenData = '/path/to/trackyou-opendata';

// Folder where TrackYou originally uploaded files are archived
$folderTrackYouArchive = '/path/to/trackyou-archive';

$xslTrackYouConvertRegistrations = '/path/to/xsl/gccgritting-convert-registrations.xsl';

$vehicleRegistrationsFilename = '/path/to/php/registrations/gccgritting-registrations.php';

$xslTrackYouConvertXMLToKML = '/path/to/xsl/gccgritting-convert-xmltokml.xsl';